### ISSUE TITLE
Is there an alternative for whole.db?

### ISSUE THREAD

**Issue by hwoihann** [bioinfo-ibms-pumc/SCSA#15]
When I run the command to analyze the seurat-generated data, it report with error:

```
Traceback (most recent call last):
  File "/home/whh/tools/SCSA/SCSA.py", line 1284, in <module>
    p.run_cmd(args)
  File "/home/whh/tools/SCSA/SCSA.py", line 1250, in run_cmd
    outs = anno.run_detail_cmd()
  File "/home/whh/tools/SCSA/SCSA.py", line 1166, in run_detail_cmd
    outs = self.calcu_seurat_group(self.args.input,self.args.Gensymbol)
  File "/home/whh/tools/SCSA/SCSA.py", line 455, in calcu_seurat_group
    self.deal_with_badtype(cname,other_gene_names,colnames)
  File "/home/whh/tools/SCSA/SCSA.py", line 223, in deal_with_badtype
    outs = self.do_go_annotation(f,fset,bset,cname,names[i][0])
  File "/home/whh/tools/SCSA/SCSA.py", line 106, in do_go_annotation
    used['go_name'] = used['ids'].map(lambda x:self.gos[x])
  File "/home/whh/miniconda3/envs/py3.6/lib/python3.6/site-packages/pandas/core/series.py", line 3983, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/home/whh/miniconda3/envs/py3.6/lib/python3.6/site-packages/pandas/core/base.py", line 1160, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2403, in pandas._libs.lib.map_infer
  File "/home/whh/tools/SCSA/SCSA.py", line 106, in <lambda>
    used['go_name'] = used['ids'].map(lambda x:self.gos[x])
KeyError: 'GO:0062103'
```
 The key error `KeyError: 'GO:0062103'` may hinted that my gene name is not included  in the annotation database?

**Comment by bioinfo-ibms-pumc** [comment]
Sorry for delay. Sometimes I can't open the Github website. It seems like go id or something can't be found from the error. Would you please send me a copy of your csv file if possible? My email is yhcao@ibms.pumc.edu.cn.  In that case I can trace the error and fix it. Thank you very much.

**Comment by cnwokolo2** [comment]
Hi, I'm having this same problem. Can I also send you my csv file?

**Comment by zqmiao-mzq** [comment]
@bioinfo-ibms-pumc any solution about this issue? I got exactly same problem. waiting for your reply.
