### ISSUE TITLE
TypeError: __cinit__() takes at least 2 positional arguments (0 given)

### ISSUE THREAD

**Issue by cnwokolo2** [bioinfo-ibms-pumc/SCSA#17]
Hi, when I run this code "python3 SCSA.py -d whole.db -s seurat -i AllMarkers.csv -k All -E -g Mouse -p 0.01 -f 1 -m txt -o testout -c 1"
I keep getting this error:
Traceback (most recent call last):
  File ".../SCSA.py", line 1284, in <module>
    p.run_cmd(args)
  File ".../SCSA.py", line 1249, in run_cmd
    anno.load_pickle_module(rdbname)
  File ".../SCSA.py", line 1070, in load_pickle_module
    self.human_gofs = load(handler)
  File "pandas/_libs/internals.pyx", line 572, in pandas._libs.internals.BlockManager.__cinit__
TypeError: __cinit__() takes at least 2 positional arguments (0 given)

**Comment by olgabaranov** [comment]
A quick fix is to install python 3.7 and run the script with it

**Comment by cnwokolo2** [comment]
@olgabaranov I appreciate your suggestion. I have python 3.9.1 currently and it is still giving the same error with it.

**Comment by olgabaranov** [comment]
@cnwokolo2   It's more about downgrading it. There was considerable change from python3.7 to 3.8, so many things that worked on 3.7 no longer work on newer versions

**Comment by cnwokolo2** [comment]
@olgabaranov I just did and I am still getting the same error .

**Comment by olgabaranov** [comment]
@cnwokolo2 okay, than I am out of clues; in my case it works with Python 3.7.11 (default, Jul  3 2021, 17:58:19)  [GCC 9.3.0] on linux (but has other issues related to Seurat v4)

**Comment by bioinfo-ibms-pumc** [comment]
Sorry for delay. I agree with @olgabaranov . This is due to the incompatible version check for the pickle and pandas module. Here is my python environment and it works for me: python: v3.8.8 ;  pandas: v1.2.4. You downgrade your python and reinstall the pandas package to have a try.
