### ISSUE TITLE
excel(ms-excel) output error

### ISSUE THREAD

**Issue by krayon4river** [bioinfo-ibms-pumc/SCSA#32]
hi,
i encountered an error when running the SCSA.py as following 
 python3 /home/Group/singleCell/Software/SCSA/SCSA.py -d $db_whole -s seurat -i $markers -k All -E -g Human -p 0.01 -f 1.5 -o $output/scCATCH_$libraryID &> $output/SCSA.out

the error :
Other Gene number: 411
Traceback (most recent call last):
  File "/home/Group/singleCell/Software/SCSA/SCSA.py", line 1284, in <module>
    p.run_cmd(args)
  File "/home/Group/singleCell/Software/SCSA/SCSA.py", line 1250, in run_cmd
    outs = anno.run_detail_cmd()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Group/singleCell/Software/SCSA/SCSA.py", line 1166, in run_detail_cmd
    outs = self.calcu_seurat_group(self.args.input,self.args.Gensymbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Group/singleCell/Software/SCSA/SCSA.py", line 464, in calcu_seurat_group
    self.wbgo.close()
  File "/home/Group/singleCell/Software/anaconda3/envs/scCATCH/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1480, in close
    self._save()
  File "/home/Group/singleCell/Software/anaconda3/envs/scCATCH/lib/python3.11/site-packages/pandas/io/excel/_openpyxl.py", line 109, in _save
    self.book.save(self._handles.handle)
  File "/home/Group/singleCell/Software/anaconda3/envs/scCATCH/lib/python3.11/site-packages/openpyxl/workbook/workbook.py", line 386, in save
    save_workbook(self, filename)
  File "/home/Group/singleCell/Software/anaconda3/envs/scCATCH/lib/python3.11/site-packages/openpyxl/writer/excel.py", line 291, in save_workbook
    archive = ZipFile(filename, 'w', ZIP_DEFLATED, allowZip64=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Group/singleCell/Software/anaconda3/envs/scCATCH/lib/python3.11/zipfile.py", line 1308, in __init__
    self.start_dir = self.fp.tell()
                     ^^^^^^^^^^^^^^
ValueError: I/O operation on closed file  

However ，I found that  it generated the excel file, but first of all,i didnt'know  what led to the error when output format was excel （txt output was okay）； Secondly  whether the content of the excel  output was complete.

Looking forward to the reply ，thanks！！

**Comment by rrllab** [comment]
same problem, must set -m txt, then the output is normal
