### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by levinhein** [bioinfo-ibms-pumc/SCSA#8]
Hi. My run failed. May I ask how can I resolve this? I downloaded your "whole.db" and "user.table" here in your Github files as input to this script. May I ask what wrong I am doing and what should I do? Thank you!

```
(base) levin@ubuntu:~$ python3 /home/levinbioinformatics/SCSA/SCSA.py -d whole.db -i all_markers.csv -s seurat -E -f1.5 -p 0.01 -o result -m txt -M user.table -E --Gensymbol
Version V1.1 [2020/07/03]
DB load: 47347 3 3 48257 37440
Namespace(Gensymbol=True, MarkerDB='user.table', celltype='normal', cluster='all', db='whole.db', foldchange=1.5, input='all_markers.csv', list_tissue=False, noprint=False, norefdb=False, outfmt='txt', output='result', pvalue=0.01, source='seurat', species='Human', target='cellmarker', tissue='All', weight=100.0)
Version V1.1 [2020/07/03]
DB load: 47347 3 3 48257 37440
load markers: 45409
User cells: 7
User genes: 22
############################## Cluster 0 ##############################

!WARNING3:Zero marker sets found, type:marker
!WARNING3:Change the threshold or tissue name and try again?
!WARNING3:EnsemblID or GeneID,try '-E' command?
!WARNING3:Zero marker sets found, type:marker
!WARNING3:Change the threshold or tissue name and try again?
!WARNING3:EnsemblID or GeneID,try '-E' command?
!WARNING3:Zero marker sets found, type:user_marker
!WARNING3:Change the threshold or tissue name and try again?
!WARNING3:EnsemblID or GeneID,try '-E' command?
Traceback (most recent call last):
  File "/home/levinbioinformatics/SCSA/SCSA.py", line 1277, in <module>
    p.run_cmd(args)
  File "/home/levinbioinformatics/SCSA/SCSA.py", line 1243, in run_cmd
    outs = anno.run_detail_cmd()
  File "/home/levinbioinformatics/SCSA/SCSA.py", line 1159, in run_detail_cmd
    outs = self.calcu_seurat_group(self.args.input,self.args.Gensymbol)
  File "/home/levinbioinformatics/SCSA/SCSA.py", line 432, in calcu_seurat_group
    h_values,colnames = self.get_cell_matrix(newexps,ltitle,fid,gcol,ccol,abs_tag)
  File "/home/levinbioinformatics/SCSA/SCSA.py", line 947, in get_cell_matrix
    return DataFrame(),set(colnames)
TypeError: 'NoneType' object is not iterable

```

![image](https://user-images.githubusercontent.com/68268222/96910824-9c209200-14d2-11eb-8b95-06f44ce7a741.png)

**Comment by bioinfo-ibms-pumc** [comment]
Sorry for inconvenience. Could you send me the file all_markers.csv ? My email is yhcao@ibms.pumc.edu.cn. I'll check it.
